[package]
name = "field"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
rand_core = "0.6.4"
num-bigint = "0.4.6"
ff = "0.13.0"
cfg-if = "1.0.0"
subtle = "2.6.1"
sp1-zkvm = { path = "../../sp1/zkvm/entrypoint" }
sp1-derive = { path = "../../sp1/derive" }
